#!/bin/sh
zip -r histogram.zip histogram/ && \
spark-submit --master yarn-cluster --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.executorEnv.PIDCLIENT_LOGGERS=kafka --conf spark.executorEnv.PIDCLIENT_KAFKA_TOPIC=pid_2_es --conf spark.yarn.appMasterEnv.PIDCLIENT_LOGGERS=kafka --conf spark.yarn.appMasterEnv.PIDCLIENT_KAFKA_TOPIC=pid_2_es --files log4j.properties --py-files histogram.zip spark.py
