#!/bin/sh

export PIDCLIENT_LOGGERS=kafka
export PIDCLIENT_KAFKA_TOPIC=pid_2_es
export PIDCLIENT_KAFKA_BROKERS=epod-master1.vgt.vito.be:6668,epod-master2.vgt.vito.be:6668,epod-master3.vgt.vito.be:6668
spark-submit  --master local[*] --conf spark.driver.bindAddress=127.0.0.1 --conf spark.eventLog.enabled=false spark.py
